name: Irrational Realm
favicon: null
layout_spectrum: 0.91486
typography_spectrum: 0.35431
title: Irrational Realm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6f6f6'
    - '#cacaca'
    - '#363636'
    - '#989898'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
